### ISSUE TITLE
Wordpress custom post types are not taken into account.

### ISSUE THREAD

**Issue by romainmenke** [coreruleset/wordpress-rule-exclusions-plugin#24]
Some rules have hard coded options for possible content types, e.g. `post`, `page`, but these do not take into account that theme developers might add custom post types.

For example rule with id `9507140` : 

```diff
# Gutenberg
- SecRule REQUEST_FILENAME "@rx /wp-json/wp/v[0-9]+/(?:posts|pages)" \
+ SecRule REQUEST_FILENAME "@rx /wp-json/wp/v[0-9]+/(?:[-_a-z0-9]+)" \
    "id:9507140,\
```

**Comment by azurit** [comment]
@romainmenke WordPress exclusion rules plugin, currently, works only with vanilla WordPress and there is no support for plugins and themes.

**Comment by romainmenke** [comment]
That is understandable 👍 
Thank you
