### ISSUE TITLE
Wordpress Site Health is unavailable

### ISSUE THREAD

**Issue by HQuest** [coreruleset/wordpress-rule-exclusions-plugin#3]
With CSR 4.0.0 RC1 (actually any CSR version since 3.0.0), the Wordpress "Tools > Site Health" functionality does not work, as the page has the string "session_start()" in the body, which is currently marked as data leakage. An exception for this particular file "site-health.php" from Wordpress could be considered, assuming no other security issues arose in doing so.

**Comment by azurit** [comment]
Hi and thanks for reporting this! Can you send full error log?

**Comment by HQuest** [comment]
[wp-site_health.log](https://github.com/coreruleset/wordpress-rule-exclusions-plugin/files/8741290/wp-site_health.log)

**Comment by azurit** [comment]
Are you sure you are using the latest exclusion rules? Problem you encountered should be addressed by rule [9507840](https://github.com/coreruleset/wordpress-rule-exclusions-plugin/blob/d143dafdbe3333665e1f83773ab78a4355f61c58/plugins/wordpress-rule-exclusions-before.conf#L719).

**Comment by theMiddleBlue** [comment]
closing this for now, feel free to reopen if there're updates
